// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

public partial class MainWindow {
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        Name = "MainWindow";
        Title = Mono.Unix.Catalog.GetString("MainWindow");
        WindowPosition = ((Gtk.WindowPosition)(4));
        if ((Child != null))
        {
            Child.ShowAll();
        }
        DefaultWidth = 400;
        DefaultHeight = 300;
        Show();
        DeleteEvent += onDeleteEvent;
    }
}
