
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox equationVbox;
	private global::Gtk.HBox equationClearHbox;
	private global::Gtk.DrawingArea equationArea;
	private global::Gtk.Button buttonBackspace;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Button button7;
	private global::Gtk.Button button4;
	private global::Gtk.Button button1;
	private global::Gtk.Button button0;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Button button8;
	private global::Gtk.Button button5;
	private global::Gtk.Button button2;
	private global::Gtk.Button buttonDot;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Button button9;
	private global::Gtk.Button button6;
	private global::Gtk.Button button3;
	private global::Gtk.Button buttonClear;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Button buttonDivide;
	private global::Gtk.Button buttonMultiply;
	private global::Gtk.Button buttonSubtract;
	private global::Gtk.Button buttonAdd;
	private global::Gtk.Button buttonExponent;
	private global::Gtk.VBox vbox5;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button buttonOpenParenthesis;
	private global::Gtk.Button buttonClosedParenthesis;
	private global::Gtk.Button buttonEquals;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Snazzy Calculator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 500;
		this.DefaultHeight = 480;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.equationVbox = new global::Gtk.VBox ();
		this.equationVbox.Name = "equationVbox";
		this.equationVbox.Spacing = 6;
		// Container child equationVbox.Gtk.Box+BoxChild
		this.equationClearHbox = new global::Gtk.HBox ();
		this.equationClearHbox.Name = "equationClearHbox";
		this.equationClearHbox.Spacing = 6;
		// Container child equationClearHbox.Gtk.Box+BoxChild
		this.equationArea = new global::Gtk.DrawingArea ();
		this.equationArea.Name = "equationArea";
		this.equationClearHbox.Add (this.equationArea);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.equationClearHbox [this.equationArea]));
		w1.Position = 0;
		// Container child equationClearHbox.Gtk.Box+BoxChild
		this.buttonBackspace = new global::Gtk.Button ();
		this.buttonBackspace.HeightRequest = 75;
		this.buttonBackspace.CanFocus = true;
		this.buttonBackspace.Name = "buttonBackspace";
		this.buttonBackspace.UseStock = true;
		this.buttonBackspace.UseUnderline = true;
		this.buttonBackspace.Label = "gtk-undo";
		this.equationClearHbox.Add (this.buttonBackspace);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.equationClearHbox [this.buttonBackspace]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.equationVbox.Add (this.equationClearHbox);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.equationVbox [this.equationClearHbox]));
		w3.Position = 0;
		w3.Expand = false;
		// Container child equationVbox.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button ();
		this.button7.WidthRequest = 90;
		this.button7.HeightRequest = 75;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.vbox6.Add (this.button7);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button7]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.WidthRequest = 90;
		this.button4.HeightRequest = 75;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.vbox6.Add (this.button4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button4]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 90;
		this.button1.HeightRequest = 75;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.vbox6.Add (this.button1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button1]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.button0 = new global::Gtk.Button ();
		this.button0.WidthRequest = 90;
		this.button0.HeightRequest = 75;
		this.button0.CanFocus = true;
		this.button0.Name = "button0";
		this.button0.UseUnderline = true;
		this.button0.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.vbox6.Add (this.button0);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button0]));
		w7.PackType = ((global::Gtk.PackType)(1));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox1.Add (this.vbox6);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox6]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button ();
		this.button8.WidthRequest = 90;
		this.button8.HeightRequest = 75;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.vbox4.Add (this.button8);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button8]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.WidthRequest = 90;
		this.button5.HeightRequest = 75;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.vbox4.Add (this.button5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button5]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.WidthRequest = 90;
		this.button2.HeightRequest = 75;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.vbox4.Add (this.button2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button2]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.buttonDot = new global::Gtk.Button ();
		this.buttonDot.WidthRequest = 90;
		this.buttonDot.HeightRequest = 75;
		this.buttonDot.CanFocus = true;
		this.buttonDot.Name = "buttonDot";
		this.buttonDot.UseUnderline = true;
		this.buttonDot.Label = global::Mono.Unix.Catalog.GetString (".");
		this.vbox4.Add (this.buttonDot);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.buttonDot]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.WidthRequest = 90;
		this.button9.HeightRequest = 75;
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.vbox3.Add (this.button9);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button9]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.WidthRequest = 90;
		this.button6.HeightRequest = 75;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.vbox3.Add (this.button6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button6]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.WidthRequest = 90;
		this.button3.HeightRequest = 75;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.vbox3.Add (this.button3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button3]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.buttonClear = new global::Gtk.Button ();
		this.buttonClear.HeightRequest = 75;
		this.buttonClear.CanFocus = true;
		this.buttonClear.Name = "buttonClear";
		this.buttonClear.UseStock = true;
		this.buttonClear.UseUnderline = true;
		this.buttonClear.Label = "gtk-clear";
		this.vbox3.Add (this.buttonClear);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.buttonClear]));
		w17.PackType = ((global::Gtk.PackType)(1));
		w17.Position = 3;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.buttonDivide = new global::Gtk.Button ();
		this.buttonDivide.WidthRequest = 90;
		this.buttonDivide.HeightRequest = 59;
		this.buttonDivide.CanFocus = true;
		this.buttonDivide.Name = "buttonDivide";
		this.buttonDivide.UseUnderline = true;
		this.buttonDivide.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.vbox7.Add (this.buttonDivide);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.buttonDivide]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.buttonMultiply = new global::Gtk.Button ();
		this.buttonMultiply.HeightRequest = 59;
		this.buttonMultiply.CanFocus = true;
		this.buttonMultiply.Name = "buttonMultiply";
		this.buttonMultiply.UseUnderline = true;
		this.buttonMultiply.Label = global::Mono.Unix.Catalog.GetString ("x");
		this.vbox7.Add (this.buttonMultiply);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.buttonMultiply]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.buttonSubtract = new global::Gtk.Button ();
		this.buttonSubtract.HeightRequest = 59;
		this.buttonSubtract.CanFocus = true;
		this.buttonSubtract.Name = "buttonSubtract";
		this.buttonSubtract.UseUnderline = true;
		this.buttonSubtract.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.vbox7.Add (this.buttonSubtract);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.buttonSubtract]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.buttonAdd = new global::Gtk.Button ();
		this.buttonAdd.HeightRequest = 59;
		this.buttonAdd.CanFocus = true;
		this.buttonAdd.Name = "buttonAdd";
		this.buttonAdd.UseUnderline = true;
		this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.vbox7.Add (this.buttonAdd);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.buttonAdd]));
		w22.Position = 3;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.buttonExponent = new global::Gtk.Button ();
		this.buttonExponent.HeightRequest = 58;
		this.buttonExponent.CanFocus = true;
		this.buttonExponent.Name = "buttonExponent";
		this.buttonExponent.UseUnderline = true;
		this.buttonExponent.Label = global::Mono.Unix.Catalog.GetString ("^");
		this.vbox7.Add (this.buttonExponent);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.buttonExponent]));
		w23.Position = 4;
		w23.Expand = false;
		w23.Fill = false;
		this.hbox1.Add (this.vbox7);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox7]));
		w24.Position = 3;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonOpenParenthesis = new global::Gtk.Button ();
		this.buttonOpenParenthesis.WidthRequest = 90;
		this.buttonOpenParenthesis.HeightRequest = 75;
		this.buttonOpenParenthesis.CanFocus = true;
		this.buttonOpenParenthesis.Name = "buttonOpenParenthesis";
		this.buttonOpenParenthesis.UseUnderline = true;
		this.buttonOpenParenthesis.Label = global::Mono.Unix.Catalog.GetString ("(");
		this.hbox2.Add (this.buttonOpenParenthesis);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonOpenParenthesis]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonClosedParenthesis = new global::Gtk.Button ();
		this.buttonClosedParenthesis.WidthRequest = 90;
		this.buttonClosedParenthesis.CanFocus = true;
		this.buttonClosedParenthesis.Name = "buttonClosedParenthesis";
		this.buttonClosedParenthesis.UseUnderline = true;
		this.buttonClosedParenthesis.Label = global::Mono.Unix.Catalog.GetString (")");
		this.hbox2.Add (this.buttonClosedParenthesis);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonClosedParenthesis]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonEquals = new global::Gtk.Button ();
		this.buttonEquals.CanDefault = true;
		this.buttonEquals.CanFocus = true;
		this.buttonEquals.Name = "buttonEquals";
		this.buttonEquals.UseUnderline = true;
		this.buttonEquals.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.hbox2.Add (this.buttonEquals);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonEquals]));
		w28.Position = 2;
		this.vbox5.Add (this.hbox2);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
		w29.Position = 0;
		this.vbox2.Add (this.vbox5);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox5]));
		w30.Position = 1;
		this.equationVbox.Add (this.vbox2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.equationVbox [this.vbox2]));
		w31.Position = 1;
		this.Add (this.equationVbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.buttonEquals.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnKeyReleaseEvent);
		this.equationArea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnEquationAreaExposeEvent);
		this.buttonBackspace.Clicked += new global::System.EventHandler (this.OnButtonBackspaceClicked);
		this.buttonBackspace.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonBackspaceExposeEvent);
		this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
		this.button7.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton7ExposeEvent);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		this.button4.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton4ExposeEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button1.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton1ExposeEvent);
		this.button0.Clicked += new global::System.EventHandler (this.OnButton0Clicked);
		this.button0.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton0ExposeEvent);
		this.button8.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
		this.button8.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton8ExposeEvent);
		this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
		this.button5.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton5ExposeEvent);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button2.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton2ExposeEvent);
		this.buttonDot.Clicked += new global::System.EventHandler (this.OnButtonDotClicked);
		this.buttonDot.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonDotExposeEvent);
		this.button9.Clicked += new global::System.EventHandler (this.OnButton9Clicked);
		this.button9.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton9ExposeEvent);
		this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
		this.button6.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton6ExposeEvent);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.button3.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButton3ExposeEvent);
		this.buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		this.buttonClear.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonClearExposeEvent);
		this.buttonDivide.Clicked += new global::System.EventHandler (this.OnButtonDivideClicked);
		this.buttonDivide.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonDivideExposeEvent);
		this.buttonMultiply.Clicked += new global::System.EventHandler (this.OnButtonMultiplyClicked);
		this.buttonMultiply.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonMultiplyExposeEvent);
		this.buttonSubtract.Clicked += new global::System.EventHandler (this.OnButtonSubtractClicked);
		this.buttonSubtract.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonSubtractExposeEvent);
		this.buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonAddClicked);
		this.buttonAdd.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonAddExposeEvent);
		this.buttonExponent.Clicked += new global::System.EventHandler (this.OnButtonExponentClicked);
		this.buttonExponent.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonExponentExposeEvent);
		this.buttonOpenParenthesis.Clicked += new global::System.EventHandler (this.OnButtonOpenParenthesisClicked);
		this.buttonOpenParenthesis.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonOpenParenthesisExposeEvent);
		this.buttonClosedParenthesis.Clicked += new global::System.EventHandler (this.OnButtonClosedParenthesisClicked);
		this.buttonClosedParenthesis.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonClosedParenthesisExposeEvent);
		this.buttonEquals.Clicked += new global::System.EventHandler (this.OnButtonEqualsClicked);
		this.buttonEquals.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnButtonEqualsExposeEvent);
	}
}
